"
Bicolore 5431 64xx 55xx
"
Class {
	#name : 'NRBicoloreSef',
	#superclass : 'NonReguliereSef',
	#category : 'Bridge-Sef-Sef',
	#package : 'Bridge-Sef',
	#tag : 'Sef'
}

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier2 [ 

	^ ''
]

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier3 [

	^ ''
]

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier4 [

	^ ''
]

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier5 [

	^ ''
]

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier6 [

	^ ''
]

{ #category : 'accessing' }
NRBicoloreSef >> ouvPalier7 [

	^ ''
]
