"
(4441) ou (5440)
"
Class {
	#name : 'NRTricoloreSef',
	#superclass : 'NonReguliereSef',
	#category : 'Bridge-Sef-Sef',
	#package : 'Bridge-Sef',
	#tag : 'Sef'
}

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier2 [

	^ ''
]

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier3 [

	^ ''
]

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier4 [

	^ ''
]

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier5 [

	^ ''
]

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier6 [

	^ ''
]

{ #category : 'accessing' }
NRTricoloreSef >> ouvPalier7 [

	^ ''
]
